#POST http://127.0.0.1:9999/auth/oauth/token?username=admin&scope=server&grant_type=password
POST http://192.168.17.228:9999/auth/oauth/token?username=admin&scope=server&grant_type=password
Content-Type: application/x-www-form-urlencoded
Authorization: Basic dGVzdDp0ZXN0
version: 23

password=rKu1/348LvKp0rsVC06eCA==

###
